### PR TITLE
Add support for MS Style Zonefiles

### PR DESCRIPTION
**Pull request by dimitertodorov**
These changes allow support for Microsoft AD DNS zone files which were throwing errors before.

This adds handling for [AGE:***] Parameters and TXT entries enclosed in Brackets.

See the spec changes for an idea of what the entries look like.

### CODE REVIEW

**Comment by pangloss** [comment]
:+1:

**Comment by craigw** [comment]
Thanks @dimitertodorov @pangloss, I'll merge this in and deploy a new gem tomorrow morning :)

**Comment by pangloss** [comment]
Thanks!

**Comment by pangloss** [comment]
Hi @craigw sorry to bug you about it, but would you mind pushing a release if you're comfortable doing so? I need to do a release this week and would much prefer to use a released version than have to bother with a workaround.

If you've got any reservations or otherwise don't think you'll be able release today, kindly let me know so I can plan accordingly.

By the way, if want to add to your list of companies using this, please add ipam.lightmesh.com. :)

Thanks!

**Comment by craigw** [comment]
Hi @pangloss. Sorry, I should have mentioned here to let you know. I released 1.0.6 just after I merged the PR which should, unless I've totally done it wrong, include your changes.

Please have a try with 1.0.6 and let me know. Thanks again for your contribution! :)

**Comment by pangloss** [comment]
Oh great, thanks! I was just waiting to see the version bump commit, which I guess is not technically a part of releasing... :)

**Comment by craigw** [comment]
Hahah, I knew I messed something up! I'll push that tonight :+1:

**Pull request merged**
