### PR TITLE
Load the grammar and use an in-memory generated parser

### PR DESCRIPTION
**Pull request by aeden**
There is no need to generate the parser file, the grammar can be read at runtime and Treetop provides a parser class in memory.

I've also updated the specs to the "expect" syntax to remove warnings.

One note: I get several warnings when loading the grammar: "Extraneous module ignored with nested atomic". Maybe there is something in the grammar that should not be there?

### CODE REVIEW

**Comment by craigw** [comment]
Awesome, thanks @aeden, and ⭐ bonus points for converting to the modern RSpec syntax 😄

It frustrated me that Treetop doesn't let us specify a namespace for the classes it generates, but I guess them's the breaks!

Happy to merge this whenever you're ready, just give me a yell to confirm you're happy with it 👍

**Comment by aeden** [comment]
Given the parser should never be used directly, I quickly got over the naming issue. ;-)

As long as the specs pass I'm fine with merging it. Once it's merged I will start submitting PRs to bring in some of the changes we have applied for DNSimple.

**Comment by aeden** [comment]
Oh yeah, I didn't bump the version in this PR, do you want me to?

**Comment by craigw** [comment]
Oh that sounds exciting, I look forward to it! Thanks for your contribution ❤️ 

Just waiting for Travis to finish running the tests and I'll hit the button. Is it worth releasing a new version at that point do you think, or shall I hold off until the other features you'd like to add have been merged?

**Comment by aeden** [comment]
I think it's worth bumping to a newer minor version, just in case someone is depending on that generated parser file.

**Comment by craigw** [comment]
👍 sounds good. Once the tests have passed I'll do that.

**Comment by aeden** [comment]
Something doesn't seem right with the ree build. It's just stuck and not even starting. Is it necessary?

**Comment by craigw** [comment]
I don't think so - I don't use REE, I think I just added it to be enthusiastic. I'll remove it.

**Comment by craigw** [comment]
👍 I've just pushed 1.1.0 which includes this PR. Thank you :)

**Comment by aeden** [comment]
Turns out I don't need to bring in our other upstream changes as:

1. They exist to handle edge cases for other providers who are exporting incorrectly formatted zone files.
2. It is possible to use grammar composition in treetop, which means I now have a grammar that I load in addition to the base dns-zonefile grammar which introduces those edge case changes.

All in all I am happy about this change. 😄 

One issue that still exists is verbosity of the treetop compiler when the grammar file is loaded. It doesn't show up when I run the specs for dns-zonefile directly, but it is showing up when I run the specs for our application. I may try to dig into that next.

**Pull request merged**
